#!/usr/bin/env bash
# Idempotent: create the dedicated "worldbuilders" DB + role.
#
# Per Q085 (postgis-schema): ONE role, ONE database, 127.0.0.1:5432 only.
# NEVER reach into /srv/shared/ Postgres; this is the project's own DB.
#
# Usage:
#   PGSUPERUSER=postgres ./backend/scripts/db-create.sh                # uses peer auth via sudo -u postgres
#   WB_DB_PASSWORD=... ./backend/scripts/db-create.sh                  # set role password (default: random)
#
# Outputs the connection URL on stdout (without password) and writes the
# password-bearing URL into backend/db/.env (chmod 600).

set -euo pipefail

DB_NAME="${WB_DB_NAME:-worldbuilders}"
DB_ROLE="${WB_DB_ROLE:-worldbuilders}"
DB_HOST="${WB_DB_HOST:-127.0.0.1}"
DB_PORT="${WB_DB_PORT:-5432}"
PGSUPERUSER="${PGSUPERUSER:-postgres}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${REPO_ROOT}/backend/db/.env"

# Generate password if not supplied; never echo it.
if [[ -z "${WB_DB_PASSWORD:-}" ]]; then
    WB_DB_PASSWORD="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)"
fi

psql_super() {
    # Peer-auth as the postgres superuser. Requires sudo without password OR
    # running this script under the postgres OS user.
    if [[ "$(id -un)" == "${PGSUPERUSER}" ]]; then
        psql -v ON_ERROR_STOP=1 "$@"
    else
        sudo -n -u "${PGSUPERUSER}" psql -v ON_ERROR_STOP=1 "$@"
    fi
}

# Create role idempotently.
psql_super -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_ROLE}'" | grep -q 1 || \
    psql_super -c "CREATE ROLE ${DB_ROLE} LOGIN PASSWORD '${WB_DB_PASSWORD}';"

# Always (re)apply password if WB_DB_PASSWORD is explicitly supplied via env.
if [[ -n "${WB_DB_PASSWORD_FORCE:-}" ]]; then
    psql_super -c "ALTER ROLE ${DB_ROLE} WITH LOGIN PASSWORD '${WB_DB_PASSWORD}';"
fi

# Create database idempotently, owned by the worldbuilders role.
psql_super -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
    psql_super -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_ROLE};"

# PostGIS extension must be created by a superuser.
psql_super -d "${DB_NAME}" -c "CREATE EXTENSION IF NOT EXISTS postgis;"
psql_super -d "${DB_NAME}" -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
psql_super -d "${DB_NAME}" -c "CREATE EXTENSION IF NOT EXISTS btree_gist;"

# Grant create on the database to the wb role so migrations can create schemas.
psql_super -d "${DB_NAME}" -c "GRANT ALL ON DATABASE ${DB_NAME} TO ${DB_ROLE};"
# Ensure schemas owned by the role (created by V0001 migration anyway, but be safe).
psql_super -d "${DB_NAME}" -c "ALTER SCHEMA public OWNER TO ${DB_ROLE};"

# Write .env file consumed by sqlx-cli + the Rust connection helper.
mkdir -p "$(dirname "${ENV_FILE}")"
umask 077
cat >"${ENV_FILE}" <<EOF
# Generated by db-create.sh — DO NOT commit. backend/db/.env is gitignored.
DATABASE_URL=postgres://${DB_ROLE}:${WB_DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
WB_DB_NAME=${DB_NAME}
WB_DB_ROLE=${DB_ROLE}
WB_DB_HOST=${DB_HOST}
WB_DB_PORT=${DB_PORT}
EOF
chmod 600 "${ENV_FILE}"

echo "OK: database '${DB_NAME}' and role '${DB_ROLE}' ready on ${DB_HOST}:${DB_PORT}"
echo "OK: connection URL written to ${ENV_FILE} (mode 600)"
echo "OK: PostGIS, pg_trgm, btree_gist extensions installed"
