#!/usr/bin/env bash
# Run sqlx migrations against the worldbuilders database.
#
# Reads DATABASE_URL from backend/db/.env (generated by db-create.sh).
# Idempotent: sqlx tracks applied versions in the _sqlx_migrations table.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${REPO_ROOT}/backend/db/.env"
MIGRATIONS_DIR="${REPO_ROOT}/backend/db/migrations"

if [[ -f "${ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    set -a; source "${ENV_FILE}"; set +a
fi

if [[ -z "${DATABASE_URL:-}" ]]; then
    echo "ERROR: DATABASE_URL not set. Run db-create.sh first or export DATABASE_URL." >&2
    exit 1
fi

if ! command -v sqlx >/dev/null 2>&1; then
    echo "ERROR: sqlx CLI not installed. Install with:" >&2
    echo "  cargo install sqlx-cli --no-default-features --features postgres,rustls" >&2
    exit 1
fi

echo "Running sqlx migrations from ${MIGRATIONS_DIR}..."
sqlx migrate run --source "${MIGRATIONS_DIR}" --database-url "${DATABASE_URL}"

echo "Current migration state:"
sqlx migrate info --source "${MIGRATIONS_DIR}" --database-url "${DATABASE_URL}"
